go.property("price", 0)

local function set_positive_text(price)
	go.set("#label", "color", vmath.vector4(0.0431, 0.7843, 0.2667, 0.8))
	label.set_text("#label", "+" .. price)
end

local function set_negative_text(price)
	go.set("#label", "color", vmath.vector4(1, 0, 0, 1))
	label.set_text("#label", tostring(price))
end

function init(self)	
	if self.price > 0 then
		set_positive_text(self.price)
	else
		set_negative_text(self.price)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.enter then
			particlefx.play("#explosion")
			local other_id = message.other_id
			go.delete(other_id) 
		end
	end
end
