local score = 0

local function save_data()
	local data = sys.load("save_data") or {}
	data.score = score
	sys.save("save_data", data)
end

local function load_data()
	local data = sys.load("save_data")
	if data and data.score then
		score = data.score
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	load_data()
	gui.set_text(gui.get_node("score_screen"), "Score: "..score)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(gui.get_node("push_button"), action.x, action.y) then
			msg.post("/localGeneratorfactory#balls_spawn_controller", "spawn_ball")
		end
		if gui.pick_node(gui.get_node("push_extra_button"), action.x, action.y) then
			msg.post("/localGeneratorfactory#balls_spawn_controller", "spawn_balls", { count = 5 })
		end
		if gui.pick_node(gui.get_node("add_extra_balls_button"), action.x, action.y) then
			msg.post("/localGeneratorfactory#balls_spawn_controller", "add_balls", { count = 10 })
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update_timer") then
		gui.set_text(gui.get_node("timer_node"), message.text)
	end
	if message_id == hash("update_count_balls") then
		gui.set_text(gui.get_node("ball_count_screen"), message.text)
	end
	if message_id == hash("update_score") then
		score = score + message.price
		gui.set_text(gui.get_node("score_screen"), "Score: "..score)
		save_data() -- Сохраняем значение score при каждом изменении
	end
end
