go.property("ball_factory", resource.factory("/main/ball.factory"))



function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	msg.post("/localGeneratorfactory#locationGenerator", "create_pyramid", nil)	
end

function on_input(self, action_id, action)
	if action_id == hash("space") and action.pressed then

		math.randomseed(os.time())
		
		local random_number = math.random(4, 4)
		
		self.ball = factory.create("/localGeneratorfactory#ball_factory", vmath.vector3(320, 1000, 0))
		msg.post(self.ball, "start_animation", {target_basket = 1 })
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("respawn") then

		local random_offset = math.random(-15, 15)
		self.ball = factory.create("/localGeneratorfactory#ball_factory", vmath.vector3(320 + random_offset, 1000, 0))
		
	end
end
