function init(self)
	msg.post(".", "acquire_input_focus") -- <1>
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then -- <2>
		local button = gui.get_node("push_button") -- <3>
		local text = gui.get_node("text") -- <4>
		if gui.pick_node(button, action.x, action.y) then -- <5>
			msg.post("/background#main", "spawn_ball")
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update_timer") then
		gui.set_text(gui.get_node("timer_node"), message.text)
	end
end