go.property("ball_factory", resource.factory("/main/ball.factory"))
local config


function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	msg.post("/localGeneratorfactory#locationGenerator", "create_pyramid", nil)
end

function on_input(self, action_id, action)
	if action_id == hash("space") and action.pressed then
		self.ball = factory.create("/localGeneratorfactory#ball_factory", vmath.vector3(320, 1000, 0))

		--math.randomseed(os.time())
		--local random_number = math.random(1, 10)
		--msg.post(self.ball, "start_animation", {target_basket = 1 })
	end
end