function init(self)
	math.randomseed(os.time())
end

local function getRandomRecord(data)
	local records = {}

	for _, value in pairs(data) do
		for subKey, subValue in pairs(value) do
			if subKey:match("record%d+") then
				table.insert(records, subValue)
			end
		end
	end

	if #records > 0 then
		local randomIndex = math.random(1, #records)
		return records[randomIndex]
	else
		return nil
	end
end

local function loadTrajectories(filePath)
	local file = io.open(filePath, "r")
	local data = {}

	if file then
		local content = file:read("*a")
		data = json.decode(content) or {}
		file:close()
	else
		print("Файл JSON не найден")
	end

	if not data then
		data = {}
		print("JSON поврежден, не удалось извлечь данные")
	end

	local record = getRandomRecord(data)
	local trajectories = {}

	if record then
		for _, value in pairs(record) do
			local trajectory = {
				position = vmath.vector3(value.position.x, value.position.y, 0),
				delta = value.delta
			}
			table.insert(trajectories, trajectory)
		end
	end

	return trajectories
end

local function animateBallToBasket(self, filePath)
	local trajectories = loadTrajectories(filePath)
	local totalDuration = 0

	for i = 2, #trajectories do
		local position = trajectories[i].position
		local delay = trajectories[i].delta
		totalDuration = totalDuration + delay

		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, position, go.EASING_LINEAR, delay, totalDuration - delay, function()
			if i == #trajectories then
				msg.post("/localGeneratorfactory#balls_spawn_controller", "release_ball", { ball = go.get_id() })
			end
		end)
	end
end

local function resetBall(self)
	go.cancel_animations(go.get_id())
	go.set_position(vmath.vector3(320, 1000, 0))
	go.set("#sprite", "tint", vmath.vector4(1, 1, 1, 1))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_animation") then
		animateBallToBasket(self, message.records)
	elseif message_id == hash("trigger_response") then
		sound.play("#sound")
	elseif message_id == hash("reset_and_disable") then
		resetBall(self)
		msg.post(".", "disable")
	end
end
