local MAX_BALLS = 30
local RESTORE_AMOUNT = 5
local RESTORE_INTERVAL = 60
local SPAWN_INTERVAL = 0.2

local balls = 0
local ball_pool = {}
local active_balls = {}
local spawn_queue = {}
local is_spawning = false

local function saveData()
	local data = sys.load("save_data") or {}
	data.balls = balls
	sys.save("save_data", data)
end

local function loadData()
	local data = sys.load("save_data")
	if data then
		balls = data.balls or MAX_BALLS
	end

	msg.post("/background#mainScreen", "update_count_balls", { text = balls.."/"..MAX_BALLS })
end

local function getRandomBasket(baskets)
	local total_probability = 0
	for _, basket in pairs(baskets) do
		total_probability = total_probability + basket.probability
	end

	local random_value = math.random() * total_probability
	local cumulative_probability = 0

	for _, basket in pairs(baskets) do
		cumulative_probability = cumulative_probability + basket.probability
		if random_value <= cumulative_probability then
			return basket.records
		end
	end
end

local function spawnBall(self)
	if balls > 0 and #ball_pool > 0 then
		balls = balls - 1
		saveData()
		local file_path_records = getRandomBasket(self.baskets)
		local ball = table.remove(ball_pool)
		msg.post(ball, "enable")
		msg.post(ball, "start_animation", { records = file_path_records })
		msg.post("/background#mainScreen", "update_count_balls", { text = balls.."/"..MAX_BALLS })
		table.insert(active_balls, ball)
	else
		print("Больше нет шариков для создания!")
	end
end

local function spawnNextBall(self)
	if #spawn_queue > 0 then
		spawnBall(self)
		table.remove(spawn_queue, 1)
		if #spawn_queue > 0 then
			timer.delay(SPAWN_INTERVAL, false, function() spawnNextBall(self) end)
		else
			is_spawning = false
		end
	end
end

local function spawnBalls(self, count)
	if is_spawning then
		print("Шарики уже создаются!")
		return
	end

	if balls < count then
		print("Недостаточно шариков для создания!")
		return
	end

	is_spawning = true
	for _ = 1, count do
		table.insert(spawn_queue, true)
	end
	if #spawn_queue > 0 then
		spawnNextBall(self)
	end
end

local function addBalls(count)
	balls = math.min(balls + count, MAX_BALLS)
	saveData()
	msg.post("/background#mainScreen", "update_count_balls", { text = balls.."/"..MAX_BALLS })
end

local function releaseBall(message)
	local ball = message.ball
	msg.post(ball, "reset_and_disable")
	table.insert(ball_pool, ball)
	for i, active_ball in ipairs(active_balls) do
		if active_ball == ball then
			table.remove(active_balls, i)
			break
		end
	end
end

function init(self)
	loadData()
	self.restore_timer = RESTORE_INTERVAL
	msg.post(".", "acquire_input_focus")
	math.randomseed(os.time())

	self.baskets = {}

	for _ = 1, MAX_BALLS do
		local ball = factory.create("/localGeneratorfactory#ball_factory", vmath.vector3(320, 1000, 0))
		table.insert(ball_pool, ball)
		msg.post(ball, "disable")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("space") and action.pressed then
		spawnBall(self)
	end
end

function update(self, dt)
	if balls < MAX_BALLS then
		self.restore_timer = self.restore_timer - dt
		if self.restore_timer <= 0 then
			addBalls(RESTORE_AMOUNT)
			self.restore_timer = RESTORE_INTERVAL
		end
	else
		self.restore_timer = RESTORE_INTERVAL
	end

	local remaining_time = math.floor(self.restore_timer)
	if balls < MAX_BALLS then
		local minutes = math.floor(remaining_time / 60)
		local seconds = remaining_time % 60
		msg.post("/background#mainScreen", "update_timer", { text = string.format("+5 balls in %02d:%02d", minutes, seconds) })
	else
		msg.post("/background#mainScreen", "update_timer", { text = "You got all the balls" })
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("spawn_ball") then
		spawnBall(self)
	elseif message_id == hash("spawn_balls") then
		spawnBalls(self, message.count)
	elseif message_id == hash("add_balls") then
		addBalls(message.count)
	elseif message_id == hash("baskets_loaded") then
		self.baskets = message.baskets
	elseif message_id == hash("release_ball") then
		releaseBall(message)
	end
end
